function [fitresult, gof] = wheel_fit(time, wheel)
%CREATEFIT(TIME,LEFT_WHEEL)
%  Create a fit.
%
%  Data for 'left_wheel_fit' fit:
%      X Input: time
%      Y Output: wheel
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 01-Mar-2024 10:21:19


%% Fit: 'left_wheel_fit'.
[xData, yData] = prepareCurveData(time, wheel );

% Set up fittype and options.
ft = fittype( 'k*200*(1-exp(-t/tau))', 'independent', 't', 'dependent', 'y' );
excludedPoints = xData > 1;
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.706046088019609 0.0318328463774207];
opts.Exclude = excludedPoints;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'left_wheel_fit' );
h = plot( fitresult, xData, yData, excludedPoints );
legend( h, 'wheel vs. time', 'Excluded wheel vs. time', 'wheel_fit', 'Location', 'SouthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'time', 'Interpreter', 'none' );
ylabel( 'wheel', 'Interpreter', 'none' );
grid on


